### ISSUE TITLE
problems with legend using version 0.2.8

### ISSUE THREAD

**Issue by irenenirgendwo** [floledermann/mapmap.js#41]
I used a version of june, after trying to use the new js-script I got problems with the display of the legend. Only one of the color boxes in the legend is displayed.

Code with your example data:

``` javascript
          var map = mapmap('#mapE1', {locale: 'de'})
            .geometry('/austria.topojson','iso') //iso primary key
            .data('/places-AT.csv' ,'code') //code matches primary key 
            .meta({
              'population': {
                    label: "Population",
                    valueLabel: "Population",
                    domain: [0, 100000], 
                    numberFormat:'0,000',
                    color: colorbrewer.YlOrRd[5], 
                    undefinedColor: '#dddddd'
                }
            })
            .choropleth('population') 
            .legend(mapmap.legend.html({
              histogram: false,              
              labelStyle: {                 //!
                  display: 'inline-flex',  //!
                  width: '10em',             //!
                  'font-size': '12px'
              },   
              bottom: '0px'
            }))
            .hoverInfo(['name','population']);
```

css is

``` css
        .mapLegend {position: relative;left: 60%;top: 250px;width: 160px;z-index: 5;background: #fff;padding-left: 3px;padding-bottom:3px}
        .mapLegend h3 {margin-bottom: 0.5em;font-size: 12px;}
        .legendColor {width: 1.5em !important; height: 1em !important; vertical-align: middle    !important;margin-bottom: 0 !important;}
        .legendLabel {font-size: 11px;width: 120px!important}
      .legendCell.undefined {display: none;}
```
